"""add mailing address to roster

Revision ID: 498a3e4f32b5
Revises: 789df888a224
Create Date: 2026-01-13 00:22:08.965848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text
from app.state_machine.models import TextEnum
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = '498a3e4f32b5'
down_revision: Union[str, Sequence[str], None] = '789df888a224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roster', sa.Column('mailing_address_id', SqidType(), nullable=True))
    op.create_index(op.f('ix_roster_mailing_address_id'), 'roster', ['mailing_address_id'], unique=False)
    op.create_foreign_key(None, 'roster', 'addresses', ['mailing_address_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roster', type_='foreignkey')
    op.drop_index(op.f('ix_roster_mailing_address_id'), table_name='roster')
    op.drop_column('roster', 'mailing_address_id')
    # ### end Alembic commands ###
