"""add universal invitation platform fields

Revision ID: 9e98993e91a5
Revises: d6b3641dac48
Create Date: 2026-01-11 00:55:10.001504

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text

from alembic import op
from app.state_machine.models import TextEnum

# revision identifiers, used by Alembic.
revision: str = "9e98993e91a5"
down_revision: str | Sequence[str] | None = "d6b3641dac48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "campaign_guests",
        "access_level",
        existing_type=sa.VARCHAR(length=50),
        type_=TextEnum(),
        existing_nullable=False,
    )
    op.alter_column(
        "roles", "role_level", existing_type=sa.VARCHAR(length=50), type_=TextEnum(), existing_nullable=False
    )
    op.add_column(
        "team_invitation_tokens", sa.Column("invitation_type", sa.Text(), server_default="team_member", nullable=False)
    )
    op.add_column(
        "team_invitation_tokens",
        sa.Column("invitation_context", sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    )

    # Data migration: Migrate existing roster invitations to new format
    op.execute(
        sql_text("""
        UPDATE team_invitation_tokens
        SET
            invitation_type = 'roster_member',
            invitation_context = json_build_object('roster_id', roster_id)
        WHERE roster_id IS NOT NULL
    """)
    )

    public_alembic_version_arive_insert = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="INSERT",
        with_grant_option=False,
    )
    op.drop_entity(public_alembic_version_arive_insert)

    public_alembic_version_arive_select = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_alembic_version_arive_select)

    public_alembic_version_arive_update = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="UPDATE",
        with_grant_option=False,
    )
    op.drop_entity(public_alembic_version_arive_update)

    public_alembic_version_arive_delete = PGGrantTable(
        schema="public", table="alembic_version", columns=[], role="arive", grant="DELETE", with_grant_option=False
    )
    op.drop_entity(public_alembic_version_arive_delete)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_alembic_version_arive_delete = PGGrantTable(
        schema="public", table="alembic_version", columns=[], role="arive", grant="DELETE", with_grant_option=False
    )
    op.create_entity(public_alembic_version_arive_delete)

    public_alembic_version_arive_update = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="UPDATE",
        with_grant_option=False,
    )
    op.create_entity(public_alembic_version_arive_update)

    public_alembic_version_arive_select = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_alembic_version_arive_select)

    public_alembic_version_arive_insert = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="INSERT",
        with_grant_option=False,
    )
    op.create_entity(public_alembic_version_arive_insert)

    op.drop_column("team_invitation_tokens", "invitation_context")
    op.drop_column("team_invitation_tokens", "invitation_type")
    op.alter_column(
        "roles", "role_level", existing_type=TextEnum(), type_=sa.VARCHAR(length=50), existing_nullable=False
    )
    op.alter_column(
        "campaign_guests",
        "access_level",
        existing_type=TextEnum(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
