"""add roster member invitation support

Revision ID: d6b3641dac48
Revises: 789df888a224
Create Date: 2026-01-10 16:19:18.155961

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic_utils.pg_grant_table import PGGrantTable

from alembic import op
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "d6b3641dac48"
down_revision: str | Sequence[str] | None = "789df888a224"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roster", sa.Column("roster_user_id", SqidType(), nullable=True))
    op.create_index(op.f("ix_roster_roster_user_id"), "roster", ["roster_user_id"], unique=False)
    op.create_foreign_key(None, "roster", "users", ["roster_user_id"], ["id"], ondelete="SET NULL")
    op.add_column("team_invitation_tokens", sa.Column("roster_id", SqidType(), nullable=True))
    op.add_column("team_invitation_tokens", sa.Column("invited_role_level", sa.Text(), nullable=True))
    op.create_index(
        "ix_roster_invitation_pending",
        "team_invitation_tokens",
        ["team_id", "roster_id", "invited_email"],
        unique=True,
        postgresql_where=sa.text("accepted_at IS NULL AND roster_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_team_invitation_tokens_roster_id"), "team_invitation_tokens", ["roster_id"], unique=False)
    op.create_foreign_key(None, "team_invitation_tokens", "roster", ["roster_id"], ["id"], ondelete="CASCADE")
    public_alembic_version_arive_insert = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="INSERT",
        with_grant_option=False,
    )
    op.drop_entity(public_alembic_version_arive_insert)

    public_alembic_version_arive_select = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_alembic_version_arive_select)

    public_alembic_version_arive_update = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="UPDATE",
        with_grant_option=False,
    )
    op.drop_entity(public_alembic_version_arive_update)

    public_alembic_version_arive_delete = PGGrantTable(
        schema="public", table="alembic_version", columns=[], role="arive", grant="DELETE", with_grant_option=False
    )
    op.drop_entity(public_alembic_version_arive_delete)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_alembic_version_arive_delete = PGGrantTable(
        schema="public", table="alembic_version", columns=[], role="arive", grant="DELETE", with_grant_option=False
    )
    op.create_entity(public_alembic_version_arive_delete)

    public_alembic_version_arive_update = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="UPDATE",
        with_grant_option=False,
    )
    op.create_entity(public_alembic_version_arive_update)

    public_alembic_version_arive_select = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_alembic_version_arive_select)

    public_alembic_version_arive_insert = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="INSERT",
        with_grant_option=False,
    )
    op.create_entity(public_alembic_version_arive_insert)

    op.drop_constraint(None, "team_invitation_tokens", type_="foreignkey")
    op.drop_index(op.f("ix_team_invitation_tokens_roster_id"), table_name="team_invitation_tokens")
    op.drop_index(
        "ix_roster_invitation_pending",
        table_name="team_invitation_tokens",
        postgresql_where=sa.text("accepted_at IS NULL AND roster_id IS NOT NULL"),
    )
    op.drop_column("team_invitation_tokens", "invited_role_level")
    op.drop_column("team_invitation_tokens", "roster_id")
    op.drop_constraint(None, "roster", type_="foreignkey")
    op.drop_index(op.f("ix_roster_roster_user_id"), table_name="roster")
    op.drop_column("roster", "roster_user_id")
    # ### end Alembic commands ###
